name: iyzi_dart_example
description: iyzi_dart vpos example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  iyzi_dart:
    path: ../

dev_dependencies:
  lints: ^3.0.0
