name: iyzi_dart
description: "Iyzico VPOS Payment Gateway Integration"
version: 0.0.1
homepage: https://github.com/tahsin-emre/iyzi_dart.git
# author: Tahsin Emre Telli <telli@tahsinemre.com>

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  crypto:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

