name: iyzi_dart
description: "Utility toolkit for Iyzico virtual point of sale (VPOS)  Payment Gateway Integration."
version: 0.4.1
homepage: https://github.com/tahsin-emre/iyzi_dart.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
flutter:

